import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useForm, type SubmitHandler } from "react-hook-form";

enum Template {
  SPONSORSHIP,
  VENUE,
}

enum Position {
  DIRECTOR = "the Director of Sponsorships",
  REP = "a sponsorship representative",
}

type Inputs = {
  writer: string;
  position: Position;
  companyName: string;
  personName?: string;
  template: Template;
};

const Compose: NextPage = () => {
  const { data: sessionData } = useSession();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = (data) => console.log(data);

  console.log(watch("template"));
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="flex flex-col items-end  gap-3 text-white"
        >
          {/* register your input into the hook by invoking the "register" function */}
          <div className="flex flex-row">
            <p className="">Your Name:</p>
            <input
              className="ml-2 border-2 border-solid border-white bg-transparent"
              defaultValue={sessionData?.user?.name ?? ""}
              {...register("writer", { required: true })}
            />
          </div>
          <div className="flex flex-row">
            <p>Your Position:</p>
            <select
              className="ml-2 border-2 border-solid border-white bg-transparent"
              defaultValue={Position.REP}
              {...register("position", { required: true })}
            >
              <option value={Position.REP}>Representative</option>
              <option value={Position.DIRECTOR}>Director</option>
            </select>
          </div>
          <div className="flex flex-row">
            <p>Company Name:</p>
            <input
              className="ml-2 border-2 border-solid border-white bg-transparent"
              {...register("companyName", { required: true })}
            />
          </div>
          <div className="flex flex-row">
            <p>Person&apos;s name (if applicable):</p>
            <input
              className="ml-2 border-2 border-solid border-white bg-transparent"
              {...register("personName")}
            />
          </div>
          <div className="flex flex-row">
            <p>Your Name:</p>
            <select
              className="ml-2 border-2 border-solid border-white bg-transparent"
              defaultValue={Template.SPONSORSHIP}
              {...register("template", { required: true })}
            >
              <option value={Template.SPONSORSHIP}>Sponsorship</option>
              <option value={Template.VENUE}>Venue</option>
            </select>
          </div>

          <input type="submit" />
        </form>
      </main>
    </>
  );
};

export default Compose;
